[Main]
default: defect
confdir: $CFGDIR/groups.conf.d
autodir: $CFGDIR/groups.d

[genders,g]
map: nodeattr -f $CLUSTER_TOOLS_PATH/site-config/node-attributes.conf -n $GROUP
list: nodeattr -f $CLUSTER_TOOLS_PATH/site-config/node-attributes.conf -l
