# ClusterShell group definitions — replace with your cluster's configuration

[cluster2partition,p2]
map:     ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -o "%N" -p $GROUP
all:     ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -o "%N"
list:    ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -o "%R"
reverse: ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -N -o "%R" -n $NODE

[cluster2state,s2]
map:     ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -o "%N" -t $GROUP
all:     ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -o "%N"
list:    ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -o "%T" | tr -d '*~#$@+'
reverse: ssh ${USER}_adm@login.hpc.example.org -- sinfo -h -N -o "%T" -n $NODE | tr -d '*~#$@+'
cache_time: 60
