# Node attributes — replace with your cluster's node data

wlm01                   vendor:vendor1,cpu:intel,cpu-type:xeon,cpu-model:8xxx
dbm01                   vendor:vendor1,cpu:intel,cpu-type:xeon,cpu-model:8xxx
exe[0001-0010]           vendor:vendor2,cpu:amd,cpu-type:epyc,cpu-model:9xxx
sub[0001-0002]           vendor:vendor2,cpu:amd,cpu-type:epyc,cpu-model:9xxx

wlm01                   os:el9
exe[0001-0010]           os:el9

wlm01                   cluster:prod
exe[0001-0010]           cluster:prod

wlm01                   class:wlm
dbm01                   class:dbm
exe[0001-0010]           class:exe
sub[0001-0002]           class:sub

wlm01                   rack:R01
exe[0001-0010]           rack:R02
