// SPDX-FileCopyrightText: 2026 GSI Helmholtz Centre for Heavy Ion Research GmbH <http://www.gsi.de>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Package sopstest writes sops encrypted files for tests with the sops
// command, the way "sops encrypt --encrypted-regex '^(data|binaryData)$'"
// writes them, to keys generated by the test, so that no private key is
// kept in the repository.
//
// The tests need sops in PATH: mise.toml pins the version CI tests with,
// and "mise install" installs it. A test that needs it fails without it
// rather than being skipped, so that a missing sops is not mistaken for a
// passing test.
package sopstest

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// EncryptedRegex is the rule the documentation tells administrators to use.
const EncryptedRegex = "^(data|binaryData)$"

// Binary returns the sops the tests run, and fails the test when there is
// none.
func Binary(t testing.TB) string {
	t.Helper()
	path, err := exec.LookPath("sops")
	if err != nil {
		t.Fatalf("sopstest: the tests of Secret documents need sops in PATH; install the version mise.toml pins with \"mise install\": %v", err)
	}
	return path
}

// Encrypt encrypts a plaintext YAML document to the given age recipients and
// returns the file sops wrote.
func Encrypt(t testing.TB, plaintext string, recipients ...string) []byte {
	t.Helper()
	return EncryptWithRegex(t, plaintext, EncryptedRegex, recipients...)
}

// EncryptWithRegex is Encrypt with another encrypted_regex; an empty one
// encrypts every value, which is what sops does by default.
func EncryptWithRegex(t testing.TB, plaintext, regex string, recipients ...string) []byte {
	t.Helper()
	return EncryptWith(t, plaintext, Options{Regex: regex}, recipients...)
}

// Options are the settings of sops a test varies.
type Options struct {
	// Regex is the encrypted_regex; an empty one encrypts every value.
	Regex string
	// MACOnlyEncrypted computes the message authentication code over the
	// encrypted values only, as "sops --mac-only-encrypted" does.
	MACOnlyEncrypted bool
}

// EncryptWith is Encrypt with the given settings.
func EncryptWith(t testing.TB, plaintext string, opts Options, recipients ...string) []byte {
	t.Helper()
	// The setting is given in a configuration rather than as
	// --mac-only-encrypted, which sops 3.10 reads as a flag of encrypt and
	// sops 3.13 as a flag of sops itself.
	config := os.DevNull
	if opts.MACOnlyEncrypted {
		config = filepath.Join(t.TempDir(), "sops.yaml")
		if err := os.WriteFile(config, []byte("creation_rules:\n  - mac_only_encrypted: true\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	args := []string{
		"--config", config, "encrypt",
		"--input-type", "yaml", "--output-type", "yaml",
		// sops needs a name for a file it reads from stdin.
		"--filename-override", "secret.sops.yaml",
		"--age", strings.Join(recipients, ","),
	}
	if opts.Regex != "" {
		args = append(args, "--encrypted-regex", opts.Regex)
	}
	cmd := exec.Command(Binary(t), args...)
	// Encrypting needs no key and no configuration; an empty environment
	// keeps the developer's out of the fixture.
	cmd.Env = []string{"HOME=" + t.TempDir()}
	cmd.Dir = t.TempDir()
	cmd.Stdin = strings.NewReader(plaintext)
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("sopstest: sops encrypt: %v\n%s", err, stderr.String())
	}
	return stdout.Bytes()
}

// AddVaultKey adds a HashiCorp Vault master key at address to the sops
// metadata of an encrypted file, the way anyone who can write the file can:
// the message authentication code does not cover the metadata. The data key
// it claims to hold is made up, so only a request to address shows that it
// was tried.
func AddVaultKey(t testing.TB, file []byte, address string) []byte {
	t.Helper()
	const at = "\nsops:\n"
	if !strings.Contains(string(file), at) {
		t.Fatalf("sopstest: the file has no sops metadata:\n%s", file)
	}
	key := at +
		"    hc_vault:\n" +
		"        - vault_address: " + address + "\n" +
		"          engine_path: transit\n" +
		"          key_name: recovery\n" +
		"          created_at: \"2026-09-22T18:26:29Z\"\n" +
		"          enc: vault:v1:c29tZXRoaW5n\n"
	return []byte(strings.Replace(string(file), at, key, 1))
}
