// SPDX-FileCopyrightText: 2026 GSI Helmholtz Centre for Heavy Ion Research GmbH <http://www.gsi.de>
// SPDX-License-Identifier: LGPL-3.0-or-later

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerate checks that every command can be documented and every kind can
// produce a schema. A command that cannot be documented is a broken command,
// and the manual build in CI is where that would otherwise be noticed.
func TestGenerate(t *testing.T) {
	dir := t.TempDir()
	ref := filepath.Join(dir, "reference")
	schema := filepath.Join(dir, "schema")

	if err := generate(ref, schema); err != nil {
		t.Fatalf("generate failed: %v", err)
	}

	pages, err := os.ReadDir(ref)
	if err != nil {
		t.Fatal(err)
	}
	if len(pages) < 20 {
		t.Errorf("only %d reference pages were written; the tree has more commands", len(pages))
	}

	index, err := os.ReadFile(filepath.Join(ref, "_index.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(index), "---") {
		t.Error("the section page has no front matter, so Hugo would not render it")
	}

	root, err := os.ReadFile(filepath.Join(ref, "clusterctl.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"---", "title: clusterctl", "weight: 1"} {
		if !strings.Contains(string(root), want) {
			t.Errorf("the root page is missing %q", want)
		}
	}
	// A generated page must not carry a timestamp: it would change on every
	// build and turn the site into noise.
	if strings.Contains(string(root), "Auto generated by spf13/cobra on") {
		t.Error("the page carries a generation timestamp")
	}

	schemas, err := os.ReadDir(schema)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := len(schemas), 6; got != want {
		t.Errorf("%d schemas were written, want %d", got, want)
	}
}

func TestPrepend(t *testing.T) {
	got := prepend("site/content/reference/clusterctl_node_select.md")
	if !strings.Contains(got, "title: clusterctl node select") {
		t.Errorf("front matter = %q", got)
	}
}

func TestLink(t *testing.T) {
	if got, want := link("clusterctl_node.md"), "../clusterctl_node/"; got != want {
		t.Errorf("link = %q, want %q", got, want)
	}
}
