[mode:sshpass]
password_prompt: yes
ssh_path: /usr/bin/sshpass /usr/bin/ssh
scp_path: /usr/bin/sshpass /usr/bin/scp
ssh_options: -oBatchMode=no -oPreferredAuthentications=password -oPubkeyAuthentication=no

[mode:sshpass-file]
password_prompt: no
ssh_path: /usr/bin/sshpass -f password.txt /usr/bin/ssh
scp_path: /usr/bin/sshpass -f password.txt /usr/bin/scp
ssh_options: -oBatchMode=no -oPreferredAuthentications=password -oPubkeyAuthentication=no

[mode:sshpass-env]
password_prompt: no
ssh_path: /usr/bin/sshpass -e /usr/bin/ssh
scp_path: /usr/bin/sshpass -e /usr/bin/scp
ssh_options: -oBatchMode=no -oPreferredAuthentications=password -oPubkeyAuthentication=no

