${CLUSTER_NET_IPMI:-}
${CLUSTER_NET_SYS02_1:-}
${CLUSTER_NET_SYS02_2:-}
${CLUSTER_NET_SYS02_3:-}
${CLUSTER_NET_SYS02_4:-}
--remote
${CLUSTER_HOST_MGMT_GATEWAY:-}
--disable-ipv6
--daemon
--pidfile
/tmp/sshuttle-ipmi-sys02.pid
--exclude
${IP_EXCL_SYS02_HOST:-}
