// SPDX-License-Identifier: LGPL-3.0-or-later

package transport

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/GSI-HPC/clusterctl/internal/apis/v1alpha1"
	"github.com/GSI-HPC/clusterctl/internal/fileutil"
)

// generateConfig renders the ssh_config that every connection is made with.
//
// Three properties of the file matter:
//
//   - The settings clusterctl needs come first, because ssh keeps the first
//     value it obtains for a keyword.
//   - The system and user configuration is included afterwards, so that
//     crypto policies, GSSAPI settings and the administrator's own Host
//     blocks keep applying to everything not set here.
//   - Trust settings live in this file rather than in -o options, because
//     -o does not reach the hops of a ProxyJump.
func (c *Client) generateConfig() ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated by clusterctl. Edits are overwritten.\n")
	b.WriteString("#\n# Settings below win over the included files, because ssh keeps the\n")
	b.WriteString("# first value it obtains for each keyword.\n\n")

	roles := make([]string, 0, len(c.roles))
	for name := range c.roles {
		roles = append(roles, name)
	}
	sort.Strings(roles)

	// A host may serve several roles; the first role naming it decides.
	written := map[string]bool{}
	for _, name := range roles {
		role := c.roles[name]
		if role.Host == "" || written[role.Host] {
			continue
		}
		written[role.Host] = true
		if err := c.writeRoleBlock(&b, name, role); err != nil {
			return nil, err
		}
	}

	b.WriteString("Host *\n")
	c.writeGlobal(&b)

	for _, include := range c.includes() {
		fmt.Fprintf(&b, "\nInclude %s\n", include)
	}
	return []byte(b.String()), nil
}

func (c *Client) writeRoleBlock(b *strings.Builder, name string, role v1alpha1.HostRole) error {
	// The block matches the real host name rather than an invented alias, so
	// that the administrator's own blocks for that host still match when the
	// configuration below is included.
	fmt.Fprintf(b, "# role %s", name)
	if role.Description != "" {
		fmt.Fprintf(b, ": %s", role.Description)
	}
	fmt.Fprintf(b, "\nHost %s\n", role.Host)

	if role.User != "" {
		fmt.Fprintf(b, "  User %s\n", role.User)
	} else if c.defaultUser != "" {
		fmt.Fprintf(b, "  User %s\n", c.defaultUser)
	}
	if role.ForwardAgent {
		b.WriteString("  ForwardAgent yes\n")
	}
	if role.ForwardX11 {
		b.WriteString("  ForwardX11 yes\n  ForwardX11Trusted yes\n")
	}
	if role.ProxyJump != "" {
		jump, err := c.resolveJump(role.ProxyJump)
		if err != nil {
			return fmt.Errorf("role %s: %w", name, err)
		}
		fmt.Fprintf(b, "  ProxyJump %s\n", jump)
	}
	if role.ControlMaster {
		// Multiplexing is only ever enabled for gateways and hubs. A master
		// per compute node runs into sshd's MaxStartups at scale.
		fmt.Fprintf(b, "  ControlMaster auto\n  ControlPath %s\n  ControlPersist %s\n",
			c.controlPath(), seconds(c.spec.ControlPersist.Or(defaultControlPersist)))
	}
	if role.LegacyAlgorithms || c.spec.LegacyKeyTypes {
		writeLegacyAlgorithms(b)
	}
	for _, k := range sortedKeys(role.Options) {
		fmt.Fprintf(b, "  %s %s\n", k, role.Options[k])
	}
	b.WriteString("\n")
	return nil
}

func (c *Client) writeGlobal(b *strings.Builder) {
	if c.knownHosts != "" {
		fmt.Fprintf(b, "  UserKnownHostsFile %s\n", c.knownHosts)
	}
	strict := "yes"
	if c.spec.StrictHostKeyChecking != nil && !*c.spec.StrictHostKeyChecking {
		strict = "accept-new"
	}
	fmt.Fprintf(b, "  StrictHostKeyChecking %s\n", strict)
	// Without this ssh appends address based entries to the shared host key
	// file behind our back, and it does so without taking a lock.
	b.WriteString("  CheckHostIP no\n")
	b.WriteString("  HashKnownHosts no\n")
	fmt.Fprintf(b, "  ConnectTimeout %s\n", seconds(c.spec.ConnectTimeout.Or(defaultConnectTimeout)))
	if n := c.spec.ConnectionAttempts; n > 0 {
		fmt.Fprintf(b, "  ConnectionAttempts %d\n", n)
	}
	if d := c.spec.ServerAliveInterval.Get(); d > 0 {
		fmt.Fprintf(b, "  ServerAliveInterval %s\n", seconds(d))
	}
	if n := c.spec.ServerAliveCountMax; n > 0 {
		fmt.Fprintf(b, "  ServerAliveCountMax %d\n", n)
	}
	if len(c.spec.SendEnv) > 0 {
		fmt.Fprintf(b, "  SendEnv %s\n", strings.Join(c.spec.SendEnv, " "))
	}
	for _, k := range sortedKeys(c.spec.Options) {
		fmt.Fprintf(b, "  %s %s\n", k, c.spec.Options[k])
	}
}

// writeLegacyAlgorithms re-enables the RSA signature algorithms current
// OpenSSH disables.
//
// The keyword is deliberately the old PubkeyAcceptedKeyTypes rather than
// PubkeyAcceptedAlgorithms: OpenSSH 8.0, which RHEL 8 ships, aborts on the
// newer name even inside a Host block that does not match.
func writeLegacyAlgorithms(b *strings.Builder) {
	b.WriteString("  PubkeyAcceptedKeyTypes +ssh-rsa\n")
	b.WriteString("  HostKeyAlgorithms +ssh-rsa\n")
}

// includes returns the configuration files to include, skipping those that do
// not exist so that ssh never reports a missing file.
func (c *Client) includes() []string {
	var out []string
	for _, path := range c.spec.Include {
		expanded := expandHome(path)
		if _, err := os.Stat(expanded); err != nil {
			continue
		}
		out = append(out, expanded)
	}
	return out
}

// controlPath is where multiplexed sockets live. The name is kept short
// because the path goes into a unix socket, whose length is capped well below
// a normal path length.
func (c *Client) controlPath() string {
	if c.spec.ControlPath != "" {
		return expandHome(c.spec.ControlPath)
	}
	return filepath.Join(c.stateDir, "cm-%C")
}

// resolveJump turns a role name into the host to jump through, leaving a name
// that is not a role as it is.
func (c *Client) resolveJump(name string) (string, error) {
	if role, ok := c.roles[name]; ok {
		if role.Host == "" {
			return "", fmt.Errorf("role %q used as a jump host has no host name", name)
		}
		if role.User != "" {
			return role.User + "@" + role.Host, nil
		}
		return role.Host, nil
	}
	return name, nil
}

// writeConfig renders the configuration and stores it in the state
// directory, atomically and readable only by its owner.
func (c *Client) writeConfig() (string, error) {
	if err := fileutil.EnsureDir(c.stateDir); err != nil {
		return "", err
	}
	data, err := c.generateConfig()
	if err != nil {
		return "", err
	}
	path := filepath.Join(c.stateDir, "ssh_config")
	if err := fileutil.WriteAtomic(path, data, 0o600); err != nil {
		return "", err
	}
	return path, nil
}

func seconds(d interface{ Seconds() float64 }) string {
	return strconv.Itoa(int(d.Seconds()))
}

func expandHome(path string) string {
	if path == "~" || strings.HasPrefix(path, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, strings.TrimPrefix(strings.TrimPrefix(path, "~"), "/"))
		}
	}
	return path
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
