// SPDX-FileCopyrightText: 2026 GSI Helmholtz Centre for Heavy Ion Research GmbH <http://www.gsi.de>
// SPDX-License-Identifier: LGPL-3.0-or-later

package transport

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"maps"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/GSI-HPC/clusterctl/internal/apis/v1alpha1"
	"github.com/GSI-HPC/clusterctl/internal/exitcode"
	"github.com/GSI-HPC/clusterctl/internal/fileutil"
)

// generateConfig renders the ssh_config that every connection is made with.
//
// Four properties of the file matter:
//
//   - The settings clusterctl needs come first, because ssh keeps the first
//     value it obtains for a keyword.
//   - Every source of host keys other than the site's file is switched off,
//     and so is multiplexing outside the roles that ask for it, so that
//     nothing an included file says can vouch for a host.
//   - The system and user configuration is included afterwards, so that
//     crypto policies, GSSAPI settings and the administrator's own Host
//     blocks keep applying to everything not set here.
//   - Trust settings live in this file rather than in -o options, because
//     -o does not reach the hops of a ProxyJump.
func (c *Client) generateConfig() ([]byte, error) {
	if err := c.options().Validate(); err != nil {
		return nil, exitcode.Wrap(exitcode.Usage, err)
	}
	if c.knownHosts == "" {
		// ssh would fall back to ~/.ssh/known_hosts, which is not the
		// file the site keeps and reviews.
		return nil, exitcode.Errorf(exitcode.Usage,
			"ssh.knownHostsFile is not set; clusterctl checks every host key against the site's file and connects to nothing without one")
	}

	var b strings.Builder
	b.WriteString("# Generated by clusterctl. Edits are overwritten.\n")
	b.WriteString("#\n# Settings below win over the included files, because ssh keeps the\n")
	b.WriteString("# first value it obtains for each keyword.\n\n")

	bodies, err := c.roleBodies()
	if err != nil {
		return nil, exitcode.Wrap(exitcode.Usage, err)
	}
	// Roles that share a host share its block; Validate made sure they
	// agree on what goes into it.
	written := map[string]bool{}
	for _, name := range slices.Sorted(maps.Keys(c.roles)) {
		role := c.roles[name]
		if role.Host == "" || written[role.Host] {
			continue
		}
		written[role.Host] = true
		writeRoleComment(&b, name, role.Description)
		// The block matches the real host name rather than an invented
		// alias, so that the administrator's own blocks for that host
		// still match when the configuration below is included.
		fmt.Fprintf(&b, "Host %s\n%s\n", role.Host, bodies[name])
	}

	global, err := c.globalBody(c.knowsKnownHostsCommand())
	if err != nil {
		return nil, exitcode.Wrap(exitcode.Usage, err)
	}
	b.WriteString("Host *\n")
	b.WriteString(global)

	for _, include := range c.includes() {
		fmt.Fprintf(&b, "\nInclude %s\n", quote(include))
	}
	return []byte(b.String()), nil
}

// options returns what the client was built from.
func (c *Client) options() Options {
	return Options{
		SSH:            c.spec,
		Roles:          c.roles,
		StateDir:       c.stateDir,
		KnownHostsFile: c.knownHosts,
		DefaultUser:    c.defaultUser,
	}
}

// writeRoleComment names the role above its block. A description may span
// lines; each becomes a comment line of its own, so that nothing in it is
// ever read as a directive.
func writeRoleComment(b *strings.Builder, name, description string) {
	fmt.Fprintf(b, "# role %s", name)
	for i, line := range strings.Split(strings.TrimRight(description, "\n"), "\n") {
		switch {
		case i == 0 && line != "":
			fmt.Fprintf(b, ": %s", line)
		case i > 0:
			fmt.Fprintf(b, "\n#   %s", line)
		}
	}
	b.WriteString("\n")
}

// block collects the lines of one Host block and remembers the keywords it
// set, so that an option repeating one is reported rather than ignored.
type block struct {
	strings.Builder
	keys map[string]bool
}

func (b *block) set(key, format string, args ...any) {
	if b.keys == nil {
		b.keys = map[string]bool{}
	}
	b.keys[canonicalKeyword(key)] = true
	b.WriteString("  " + key + " " + fmt.Sprintf(format, args...) + "\n")
}

// options appends the configured extra keywords, refusing those this block
// or the trust settings already decide.
func (b *block) options(where string, options map[string]string, refused map[string]string) error {
	for _, k := range slices.Sorted(maps.Keys(options)) {
		key := canonicalKeyword(k)
		if why, ok := refused[key]; ok {
			return fmt.Errorf("%s: the ssh option %s is refused: %s", where, k, why)
		}
		if b.keys[key] {
			return fmt.Errorf("%s: the ssh option %s is set by clusterctl itself; use the setting clusterctl offers for it", where, k)
		}
		b.set(k, "%s", options[k])
	}
	return nil
}

// roleBodies renders the settings of every role's Host block.
func (c *Client) roleBodies() (map[string]string, error) {
	out := map[string]string{}
	for _, name := range slices.Sorted(maps.Keys(c.roles)) {
		body, err := c.roleBody(name, c.roles[name])
		if err != nil {
			return nil, err
		}
		out[name] = body
	}
	return out, nil
}

func (c *Client) roleBody(name string, role v1alpha1.HostRole) (string, error) {
	var b block
	// The role's account is not written here. The block matches the real
	// host name, so a User line would also apply to a node of that name;
	// the account goes on the command line instead, and into the jump
	// hosts that name the role.
	if role.ForwardAgent {
		b.set("ForwardAgent", "yes")
	}
	if role.ForwardX11 {
		b.set("ForwardX11", "yes")
		b.set("ForwardX11Trusted", "yes")
	}
	if role.ProxyJump != "" {
		jump, _, err := c.resolveJumps(role.ProxyJump)
		if err != nil {
			return "", fmt.Errorf("role %s: %w", name, err)
		}
		b.set("ProxyJump", "%s", jump)
	}
	if role.ControlMaster {
		// Multiplexing is only ever enabled for gateways and hubs. A master
		// per compute node runs into sshd's MaxStartups at scale.
		b.set("ControlMaster", "auto")
		b.set("ControlPath", "%s", quote(c.controlPath()))
		b.set("ControlPersist", "%s", persist(c.spec.ControlPersist.Get()))
	}
	if role.LegacyAlgorithms {
		writeLegacyAlgorithms(&b)
	}
	if err := b.options("role "+name, role.Options, roleRefused); err != nil {
		return "", err
	}
	return b.String(), nil
}

// globalBody renders the Host * block, which every connection reads.
// knownHostsCommand says whether the client understands the keyword.
func (c *Client) globalBody(knownHostsCommand bool) (string, error) {
	var b block
	// The site's file is the only place a host key is looked up. Each of
	// the other sources ssh knows is switched off here, before an include
	// can switch it on: a key any source vouches for is accepted.
	b.set("UserKnownHostsFile", "%s", quote(escapePercent(c.knownHosts)))
	b.set("GlobalKnownHostsFile", "/dev/null")
	if knownHostsCommand {
		b.set("KnownHostsCommand", "none")
	}
	strict := "yes"
	if c.spec.StrictHostKeyChecking != nil && !*c.spec.StrictHostKeyChecking {
		strict = "accept-new"
	}
	b.set("StrictHostKeyChecking", "%s", strict)
	b.set("VerifyHostKeyDNS", "no")
	b.set("NoHostAuthenticationForLocalhost", "no")
	// Without these ssh writes to the shared host key file behind our back,
	// and it does so without taking a lock.
	b.set("UpdateHostKeys", "no")
	b.set("CheckHostIP", "no")
	b.set("HashKnownHosts", "no")
	// A connection through an existing master checks no host key, so no
	// master is used unless a role above asks for its own.
	b.set("ControlMaster", "no")
	b.set("ControlPath", "none")
	b.set("ConnectTimeout", "%s", seconds(c.spec.ConnectTimeout.Or(defaultConnectTimeout)))
	if n := c.spec.ConnectionAttempts; n > 0 {
		b.set("ConnectionAttempts", "%d", n)
	}
	if d := c.spec.ServerAliveInterval.Get(); d > 0 {
		b.set("ServerAliveInterval", "%s", seconds(d))
	}
	if n := c.spec.ServerAliveCountMax; n > 0 {
		b.set("ServerAliveCountMax", "%d", n)
	}
	if len(c.spec.SendEnv) > 0 {
		b.set("SendEnv", "%s", strings.Join(c.spec.SendEnv, " "))
	}
	if c.spec.LegacyKeyTypes {
		writeLegacyAlgorithms(&b)
	}
	if err := b.options("ssh.options", c.spec.Options, globalRefused); err != nil {
		return "", err
	}
	return b.String(), nil
}

// writeLegacyAlgorithms re-enables the RSA signature algorithms current
// OpenSSH disables.
//
// The keyword is deliberately the old PubkeyAcceptedKeyTypes rather than
// PubkeyAcceptedAlgorithms: OpenSSH 8.0, which RHEL 8 ships, aborts on the
// newer name even inside a Host block that does not match.
func writeLegacyAlgorithms(b *block) {
	b.set("PubkeyAcceptedKeyTypes", "+ssh-rsa")
	b.set("HostKeyAlgorithms", "+ssh-rsa")
}

// trustKeywords decide which host keys are trusted, or bypass the check. The
// generated file sets each of them once for every host, and no option may
// set them again.
var trustKeywords = map[string]string{
	"host":                             "it would start a block of its own",
	"match":                            "it would start a block of its own",
	"include":                          "list the file under ssh.include",
	"userknownhostsfile":               "set ssh.knownHostsFile",
	"globalknownhostsfile":             "every host key is checked against ssh.knownHostsFile alone",
	"knownhostscommand":                "every host key is checked against ssh.knownHostsFile alone",
	"stricthostkeychecking":            "set ssh.strictHostKeyChecking",
	"verifyhostkeydns":                 "every host key is checked against ssh.knownHostsFile alone",
	"updatehostkeys":                   "ssh would write to the site's host key file",
	"hashknownhosts":                   "ssh would write to the site's host key file",
	"checkhostip":                      "ssh would write to the site's host key file",
	"hostkeyalias":                     "every host key is checked against ssh.knownHostsFile under the host's own name",
	"nohostauthenticationforlocalhost": "every host key is checked against ssh.knownHostsFile",
	"controlmaster":                    "set controlMaster on the role",
	"controlpath":                      "set ssh.controlPath",
}

var (
	// roleRefused adds the settings a role has a field for. A User line
	// in particular would reach a node of the same host name.
	roleRefused = merged(trustKeywords, map[string]string{
		"user":         "set user on the role",
		"proxyjump":    "set proxyJump on the role",
		"forwardagent": "set forwardAgent on the role",
		"forwardx11":   "set forwardX11 on the role",
	})
	globalRefused = trustKeywords
)

func merged(tables ...map[string]string) map[string]string {
	out := map[string]string{}
	for _, m := range tables {
		maps.Copy(out, m)
	}
	return out
}

// canonicalKeyword folds a keyword the way ssh reads it: without regard to
// case, and with the names ssh treats as one option folded together.
func canonicalKeyword(key string) string {
	key = strings.ToLower(key)
	if key == "pubkeyacceptedalgorithms" {
		return "pubkeyacceptedkeytypes"
	}
	return key
}

// knowsKnownHostsCommand reports whether the ssh client understands
// KnownHostsCommand, which OpenSSH 8.5 introduced.
//
// An older client aborts on the keyword, and IgnoreUnknown cannot be used to
// hide it: ssh keeps the first IgnoreUnknown it reads, so ours would silence
// the administrator's own. An older client cannot read the keyword from an
// include either, so leaving it out there loses nothing. When the version
// cannot be told, the keyword is written, and a client that does not know it
// refuses the file rather than trusting a command's keys.
func (c *Client) knowsKnownHostsCommand() bool {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, c.Binary(), "-V").CombinedOutput()
	if err != nil {
		return true
	}
	m := opensshVersion.FindSubmatch(out)
	if m == nil {
		return true
	}
	major, _ := strconv.Atoi(string(m[1]))
	minor, _ := strconv.Atoi(string(m[2]))
	return major > 8 || major == 8 && minor >= 5
}

var opensshVersion = regexp.MustCompile(`OpenSSH_(?:for_Windows_)?(\d+)\.(\d+)`)

// includes returns the configuration files to include, skipping those that do
// not exist so that ssh never reports a missing file. A pattern is passed on
// as it is: ssh expands it and includes nothing when nothing matches.
func (c *Client) includes() []string {
	var out []string
	for _, path := range c.spec.Include {
		expanded := expandHome(path)
		if !isGlob(expanded) {
			if _, err := os.Stat(expanded); err != nil {
				continue
			}
		}
		out = append(out, expanded)
	}
	return out
}

func isGlob(path string) bool { return strings.ContainsAny(path, "*?[") }

// controlPath is where multiplexed sockets live. The name is kept short
// because the path goes into a unix socket, whose length is capped well below
// a normal path length.
//
// The default name carries a digest of the host key file and the strictness,
// so that a master opened under one trust setting, by another context or
// another site, is never reused under a different one.
func (c *Client) controlPath() string {
	if c.spec.ControlPath != "" {
		return expandHome(c.spec.ControlPath)
	}
	return filepath.Join(escapePercent(c.stateDir), "cm-"+c.trustDigest()+"-%C")
}

func (c *Client) trustDigest() string {
	strict := c.spec.StrictHostKeyChecking == nil || *c.spec.StrictHostKeyChecking
	sum := sha256.Sum256([]byte(c.knownHosts + "\x00" + strconv.FormatBool(strict)))
	return hex.EncodeToString(sum[:4])
}

// jumpHop is one element of a ProxyJump list.
type jumpHop struct {
	user, host, port string
}

// parseHop splits [user@]host[:port], with an IPv6 address in brackets.
func parseHop(s string) (jumpHop, error) {
	var hop jumpHop
	if at := strings.LastIndex(s, "@"); at >= 0 {
		hop.user, s = s[:at], s[at+1:]
		if !validUser(hop.user) {
			return hop, fmt.Errorf("%q is not a user name", hop.user)
		}
	}
	switch {
	case strings.HasPrefix(s, "["):
		end := strings.Index(s, "]")
		if end < 0 {
			return hop, fmt.Errorf("%q has no closing bracket", s)
		}
		hop.host, s = s[1:end], s[end+1:]
		if s != "" {
			if !strings.HasPrefix(s, ":") {
				return hop, fmt.Errorf("unexpected %q after the address", s)
			}
			hop.port = s[1:]
		}
	case strings.Count(s, ":") == 1:
		hop.host, hop.port, _ = strings.Cut(s, ":")
	default:
		hop.host = s
	}
	if hop.port != "" {
		if n, err := strconv.Atoi(hop.port); err != nil || n < 1 || n > 65535 {
			return hop, fmt.Errorf("%q is not a port", hop.port)
		}
	}
	if !validHost(hop.host) {
		return hop, fmt.Errorf("%q is not a host name", hop.host)
	}
	return hop, nil
}

func (h jumpHop) String() string {
	host := h.host
	if h.port != "" {
		if strings.Contains(host, ":") {
			host = "[" + host + "]"
		}
		host += ":" + h.port
	}
	if h.user != "" {
		return h.user + "@" + host
	}
	return host
}

// resolveJumps turns a proxyJump value into the list ssh is given, and names
// the roles it goes through.
//
// Each element may name a role, with an optional account, or a host. A role
// becomes its host and account. A host that is some role's host is taken as
// that role, so that a chain through it is seen. Any other element has to be
// a fully qualified name or an address: a bare word that is not a role is
// much more likely a misspelt role than a host.
func (c *Client) resolveJumps(value string) (string, []string, error) {
	var (
		hops  []string
		roles []string
	)
	for element := range strings.SplitSeq(value, ",") {
		hop, err := parseHop(strings.TrimSpace(element))
		if err != nil {
			return "", nil, fmt.Errorf("proxyJump %q: %w", value, err)
		}
		name, isRole := hop.host, false
		if role, ok := c.roles[hop.host]; ok {
			if role.Host == "" {
				return "", nil, fmt.Errorf("role %q used as a jump host has no host name", hop.host)
			}
			hop.host, isRole = role.Host, true
		} else if byHost := c.roleByHost(hop.host); byHost != "" {
			name, isRole = byHost, true
		} else if !strings.ContainsAny(hop.host, ".:") {
			return "", nil, fmt.Errorf("proxyJump %q: %q is neither a role nor a fully qualified host name", value, hop.host)
		}
		if isRole {
			roles = append(roles, name)
			if hop.user == "" {
				hop.user = c.userFor(Target{Role: name})
			}
		}
		hops = append(hops, hop.String())
	}
	return strings.Join(hops, ","), roles, nil
}

// roleByHost returns the first role, in name order, whose host is host.
func (c *Client) roleByHost(host string) string {
	for _, name := range slices.Sorted(maps.Keys(c.roles)) {
		if c.roles[name].Host == host {
			return name
		}
	}
	return ""
}

// Validate checks everything the generated ssh configuration is built from.
//
// Each value is written into a line of the file, so a line break in one
// would add a directive and a space would split it; ssh would then reject the
// whole file, or worse, obey the line. Jump chains are checked for cycles,
// because ssh follows one without end.
func (o Options) Validate() error {
	c := New(o)
	var errs []error
	fail := func(format string, args ...any) { errs = append(errs, fmt.Errorf(format, args...)) }

	if o.KnownHostsFile != "" {
		if err := checkPath(o.KnownHostsFile); err != nil {
			fail("ssh.knownHostsFile: %w", err)
		} else if !filepath.IsAbs(o.KnownHostsFile) {
			fail("ssh.knownHostsFile %q is not an absolute path; ssh would read it relative to wherever it is run", o.KnownHostsFile)
		}
	}
	if err := checkPath(o.StateDir); err != nil {
		fail("state directory: %w", err)
	}
	if o.DefaultUser != "" && !validUser(o.DefaultUser) {
		fail("the context user %q is not a user name", o.DefaultUser)
	}
	for i, include := range o.SSH.Include {
		if err := checkPath(include); err != nil {
			fail("ssh.include[%d]: %w", i, err)
		} else if expanded := expandHome(include); !filepath.IsAbs(expanded) {
			fail("ssh.include[%d] %q is not an absolute path; ssh would read it relative to ~/.ssh", i, include)
		}
	}
	if err := checkPath(o.SSH.ControlPath); err != nil {
		fail("ssh.controlPath: %w", err)
	}
	for _, name := range o.SSH.SendEnv {
		if name == "" || strings.ContainsAny(name, " \t\"\\") || hasControl(name, false) {
			fail("ssh.sendEnv: %q is not an environment variable name", name)
		}
	}
	checkOptions := func(where string, options map[string]string) {
		for _, k := range slices.Sorted(maps.Keys(options)) {
			if !keyword.MatchString(k) {
				fail("%s: %q is not an ssh option keyword", where, k)
			}
			if v := options[k]; strings.TrimSpace(v) == "" || hasControl(v, false) {
				fail("%s: the value %q of %s is empty or holds a control character", where, v, k)
			}
		}
	}
	checkOptions("ssh.options", o.SSH.Options)

	for _, name := range slices.Sorted(maps.Keys(o.Roles)) {
		role := o.Roles[name]
		if hasControl(name, false) {
			fail("role %q: the name holds a control character", name)
		}
		if role.Host != "" && !validHost(role.Host) {
			fail("role %s: host %q is not a host name; it is written as a Host pattern, which must match that host alone", name, role.Host)
		}
		if role.User != "" && !validUser(role.User) {
			fail("role %s: %q is not a user name", name, role.User)
		}
		if hasControl(role.Description, true) {
			fail("role %s: the description holds a control character", name)
		}
		checkOptions("role "+name, role.Options)
	}
	if len(errs) > 0 {
		// The rest renders these values; it would only repeat the errors.
		return errors.Join(errs...)
	}

	bodies, err := c.roleBodies()
	if err != nil {
		errs = append(errs, err)
	}
	if _, err := c.globalBody(true); err != nil {
		errs = append(errs, err)
	}
	if err := c.checkSharedHosts(bodies); err != nil {
		errs = append(errs, err)
	}
	if err := c.checkJumpCycles(); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// checkSharedHosts refuses roles that name one host with different settings.
// A host gets one block, so the settings of all but one would be dropped.
func (c *Client) checkSharedHosts(bodies map[string]string) error {
	if bodies == nil {
		return nil
	}
	first := map[string]string{}
	var errs []error
	for _, name := range slices.Sorted(maps.Keys(c.roles)) {
		host := c.roles[name].Host
		if host == "" {
			continue
		}
		other, seen := first[host]
		if !seen {
			first[host] = name
			continue
		}
		if bodies[other] != bodies[name] {
			errs = append(errs, fmt.Errorf(
				"roles %s and %s both connect to %s with different ssh settings; a host has one block, so give them the same proxyJump, controlMaster, legacyAlgorithms, forwarding and options",
				other, name, host))
		}
	}
	return errors.Join(errs...)
}

// checkJumpCycles follows every role's jump chain. ssh starts the hops of a
// cycle before it sends a single packet, and does so without end.
func (c *Client) checkJumpCycles() error {
	next := map[string][]string{}
	for _, name := range slices.Sorted(maps.Keys(c.roles)) {
		// A value that does not resolve is reported by roleBodies.
		if jump := c.roles[name].ProxyJump; jump != "" {
			if _, roles, err := c.resolveJumps(jump); err == nil {
				next[name] = roles
			}
		}
	}
	const (
		unseen = iota
		onPath
		done
	)
	state := map[string]int{}
	var path []string
	var visit func(name string) error
	visit = func(name string) error {
		switch state[name] {
		case onPath:
			start := 0
			for i, n := range path {
				if n == name {
					start = i
				}
			}
			return fmt.Errorf("proxyJump cycle: %s", strings.Join(append(path[start:], name), " -> "))
		case done:
			return nil
		}
		state[name] = onPath
		path = append(path, name)
		for _, n := range next[name] {
			if err := visit(n); err != nil {
				return err
			}
		}
		path = path[:len(path)-1]
		state[name] = done
		return nil
	}
	for _, name := range slices.Sorted(maps.Keys(c.roles)) {
		if err := visit(name); err != nil {
			return err
		}
	}
	return nil
}

var (
	keyword  = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9]*$`)
	hostName = regexp.MustCompile(`^[A-Za-z0-9_:][A-Za-z0-9_.:-]*$`)
	userName = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9_.@-]*\$?$`)
)

// validHost accepts a host name or an address, and nothing ssh would read as
// a pattern.
func validHost(s string) bool { return hostName.MatchString(s) }

// validUser accepts an account name. It may not start with a dash, because
// user@host is an argument of its own and would otherwise be read as an
// option.
func validUser(s string) bool { return userName.MatchString(s) }

// checkPath refuses what the double quotes a path is written in cannot hold.
func checkPath(path string) error {
	switch {
	case hasControl(path, false):
		return fmt.Errorf("%q holds a control character", path)
	case strings.ContainsAny(path, `"\`):
		return fmt.Errorf("%q holds a quote or a backslash, which ssh_config cannot quote", path)
	case strings.Contains(path, "${"):
		return fmt.Errorf("%q holds ${, which ssh would expand as an environment variable", path)
	}
	return nil
}

func hasControl(s string, allowLines bool) bool {
	for _, r := range s {
		if allowLines && (r == '\n' || r == '\t') {
			continue
		}
		if r < 0x20 || r == 0x7f {
			return true
		}
	}
	return false
}

// quote writes a path as one ssh_config argument, so that a space in it, as
// in ~/Library/Application Support, does not split it in two.
func quote(path string) string { return `"` + path + `"` }

// escapePercent protects a literal % in a path from ssh's token expansion.
func escapePercent(path string) string { return strings.ReplaceAll(path, "%", "%%") }

// writeConfig renders the configuration and stores it in the state
// directory, atomically and readable only by its owner.
//
// The file is named by a digest of its content. ssh reads it again for every
// connection, so a file shared by two configurations would let one process
// connect with the trust settings another has just written. A name derived
// from the content means that a file, once written, never changes: processes
// with the same configuration share it, and a long running one, such as a
// tunnel, can keep using it after this process ends.
func (c *Client) writeConfig() (string, error) {
	data, err := c.generateConfig()
	if err != nil {
		return "", err
	}
	if err := fileutil.EnsureDir(c.stateDir); err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	path := filepath.Join(c.stateDir, "ssh_config-"+hex.EncodeToString(sum[:8]))
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, data) {
		return path, nil
	}
	if err := fileutil.WriteAtomic(path, data, 0o600); err != nil {
		return "", err
	}
	return path, nil
}

// seconds renders a duration in whole seconds, rounding up: ssh reads 0 as
// no timeout at all.
func seconds(d time.Duration) string {
	return strconv.Itoa(int(math.Ceil(d.Seconds())))
}

// persist renders ControlPersist. Zero switches persistence off, so that a
// master ends with the connection that opened it; ssh itself would read 0 as
// keeping it for ever.
func persist(d time.Duration) string {
	if d <= 0 {
		return "no"
	}
	return seconds(d)
}

func expandHome(path string) string {
	if path == "~" || strings.HasPrefix(path, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, strings.TrimPrefix(strings.TrimPrefix(path, "~"), "/"))
		}
	}
	return path
}
